package.json

Change package.json to use vladimirov/fibers_1_0_5_fixes branch where node-fibers are built with all the latest fixes. This is a temporary change that has to be removed after merging vladimirov/fibers_1_0_5_fixes into master of node-fibers repo. The temp change is required for testing purposes.

Use updated fibers

---

package.json

Add node as engine and set supported version to be at least 0.10.26 and at most 0.10.x (excluding 0.10.34).

Add supported engines

---

lib/iphone-simulator.js
lib/iphone-simulator.ts

We need this in NativeScript for iOS to start the app waiting for a debugger.

Pass the 'args' options to the simulator

---

package.json

Add support for iojs 2.x by referencing Telerik forks of Fibers and
NodObjC packages.

Add support for iojs

---

lib/declarations.ts
lib/definitions/NodObjC.d.ts
lib/iphone-simulator-xcode-5.js
lib/iphone-simulator-xcode-5.ts
lib/iphone-simulator-xcode-6.js
lib/iphone-simulator-xcode-6.ts
lib/iphone-simulator.js
lib/iphone-simulator.ts
package.json

Add support for Node 4.1.x+ by updating NodeObjC module.
It has been renamed to nodobjc, so replace the using in our code.

Add support for node 4.1.x+

---

package.json

Add support for node 5.1.x by updating references. Set node versions between 5.1.0 and 6.0.0 as verified.

Add support for node 5.1.x

---

lib/iphone-simulator-xcode-7.ts

I believe this fixes #50. The module name has changed to be lower case (NodObjC --> nodobjc). This has been changed in other source files, but looks like this file may have been overlooked, which prevented the xcode7 simulator from launching.

Fixes #50 - xcode7 sim launch error.

---

lib/declarations.ts
lib/iphone-simulator-common.ts
lib/iphone-simulator-xcode-6.ts
lib/iphone-simulator-xcode-7.ts
package.json

Add filtering for simulator logs based on the PID of the started process.
In order to use the filtering, just pass the output of startApplication method as a second parameter of printDeviceLog method.

Add filtering for simulator logs based on the PID of the started process.

---

lib/declarations.ts
lib/iphone-simulator-name-getter.ts

However, use the name passed as a command-line option with priority.
Note that ios-sim-portable should be refactored to take the currently running simulator into account on its own, instead of having to pass it as a param from the outside.
Ping @rosen-vladimirov

Respect optional deviceName parameter passed

---

lib/iphone-simulator-common.ts
package.json

When application is restarted, the PID of the process is changed. So when showing device logs, we should change the pid when the printDeviceLog is called.
Spawn the process (`tail -f ...`) only one time, but change the PID whenever the method is called.

Fix filtering of iOS Simulator logs per pid of new process

---

lib/iphone-simulator-common.ts
package.json

Some watchkit apps have xml plist file and when we try to read them as binary plists, the bplist module fails.
Catch this error and try to parse them with plist module.

Fix parsing of simulator plist files

---

package.json

Currently our CLIs install latest 1.0.x version directly. In the new version (1.0.24) the fibers module is changed which causes errors `[Object object] is not a future`. This is due to the fact that fibers module is installed in both CLI and ios-sim-portable.

Set version to 1.1.0

---

package.json
postinstall.js

When ios-sim-portable is used as dependency of any module that has fibers, the fibers in ios-sim-portable conflict at runtime with the original package's fibers.
So add postinstall script to check if there are fibers in the upper level dir and upper level dir is called node_modules. If these circumstances are fulfilled, remove the ios-sim-portable's fibers directory - let's use original package's fibers module.

Fix [object Object] is not a future

---

lib/iphone-interop-simulator-base.ts
lib/iphone-simulator-xcode-7.ts
lib/iphone-simulator.ts
lib/options.js
lib/options.ts

When CLI uses ios-sim-portable through require("ios-sim-portable"), this module must understand the same command line parameters as the one passed to NativeScript CLI / AppBuilder CLI.
The option there is called `--sdk`, while here it is `--sdkVersion`. Add `--sdk` here, so ios-sim-portable will pass it and use it to start the correct emulator.

Add --sdk as parameter

---

lib/ios-sim.ts
lib/iphone-interop-simulator-base.ts
lib/iphone-simulator-common.ts
lib/iphone-simulator-xcode-5.ts
lib/iphone-simulator-xcode-6.ts
lib/iphone-simulator-xcode-7.ts
lib/iphone-simulator.ts
lib/options.js
lib/options.ts
lib/simctl.ts

When CLI require's ios-sim-portable, it already had added lodash in the global object. So ios-sim-portable resets it to the version specified in its own package.json, so CLI's code will no longer work.
Do not use the _ from the global object - require it in each file instead.

Remove lodash from global object

---

package.json
prepublish.js

Fix prepublish script to transpile `.ts` files only when the ios-sim.ts file exists.
This will allow us to call `npm publish <path to ios-sim-portable.tgz>` without `--ignore-scripts` option as it is removing all scripts from package.json section.

Fix prepublish script

---

Gruntfile.js
package.json

Add grunt pack command that will:
* remove prepublish script from package.json
* clean the project (delete all .js files inside it)
* build .ts files in release mode
* call `npm pack` and produce .tgz for the new version
We have to remove the prepublish script as it does not allow us clean publish of the .tgz.
The problem is that when `npm publish <tgz>` is used, the package is added to local npm cache. After that it's package.json is extracted from the cached .tgz file and modified with additional metadata. At this point npm calls the prepublish script, but it fails to find our prepublish.js as it's not extracted in the cache (only the package.json is extracted).
I've not removed the prepublish script from the package.json, so if anyone uses `npm pack` locally or `npm publish` directly, …

Add grunt pack command

---

lib/declarations.ts
lib/iphone-simulator-common.ts
lib/iphone-simulator-xcode-5.ts
lib/iphone-simulator-xcode-6.ts
lib/iphone-simulator-xcode-7.ts
lib/iphone-simulator-xcode-8.ts

If someone wants to use the child process which is used to get the device log we need to return it when the printDeviceLog method is called.

Return the child process of print device log

---

lib/declarations.ts
lib/ios-sim.ts
lib/iphone-simulator-common.ts
lib/iphone-simulator-xcode-5.ts
lib/iphone-simulator-xcode-6.ts
lib/iphone-simulator-xcode-7.ts
lib/iphone-simulator-xcode-8.ts
package.json

Add `getDeviceLogProcess` method that returns child_process for device logs to the caller and let it decide how to hanlde the logging operations.

Return simulator log to caller and do not filter the output

---

lib/simctl.ts
package.json

When the device name contains `()`, the regex matches it instead of the GUID and after that we exclude the device from the list with available devices.
Such devices are:
```
iPad Pro (9.7 inch) (7FF984D4-0755-432D-BE0E-6EB44F0489CB) (Shutdown)
iPad Pro (12.9 inch) (F02012C8-6D4D-46FF-90D7-5DF90EF579E8) (Booted)
```
This way users are unable to execute any operation on such simulators.
Fix the regular expression to match based on the GUID instead of using the `(` as main part of the regex.
Check this gist for comparison of the results with the old and the new regex:
https://gist.github.com/rosen-vladimirov/85b4ccb78af2e604ac91efecd2a67150

Fix detection of iPad Pro

---

lib/declarations.ts
lib/iphone-simulator-xcode-simctl.ts
lib/simctl.ts
lib/utils.ts
lib/xcode.ts
package.json

`stopApplication` method calls `killall` command, which does not terminate the process immediately. So trying to restart the application, which is `stopApplication` followed by immediate `startApplication` call, fails with some strange error, that the `app has started, but has exited since then`. In order to fix this, add a timeout after stop is called, in order to ensure the app is dead. However in newer Xcode's there's a `xcrun simctl terminate` command, which really kills it.
So check the version of Xcode and in case it is 8 or later, use the new command instead of killall. In this scenario we do not have to add some magic timeout as the command works correctly.
However the xcrun simctl terminate command requires application identifier, while the killall command works with application …

Ensure stopApplication works correctly

---

lib/ios-sim.ts
lib/iphone-simulator-xcode-simctl.ts

Part of the fix for https://github.com/NativeScript/nativescript-cli/issues/2728. Now an exception is thrown if no simulator image is available for the specified identifier.

Fix simulator identifier not verified before startEmulator.

---

lib/iphone-simulator-xcode-simctl.ts
package.json

In case device.id is not passed, we should start the default simulator (iPhone 6 for example). However, we are searching for device with id 'undefined' and we fail. Skip the verification in case device.id is not specified.

Fix starting default simulator

---

lib/iphone-simulator-xcode-simctl.ts
package.json

In case the OS version of the simulated device is below 10, (for example 8.4) the `simctl terminate` does not kill the app immediately, so we kill it after we've called start.
Fix this by waiting 500 ms.

Fix restarting of application on simulator with OS < 10

---

lib/simctl.ts
package.json

In case when ios-sim-portable is used as a library, in a CLI for example, sending Ctrl + C should kill the CLI process and its related resources.
However, in case the code is currently executing `xcrun simctl` command, sending Ctrl + C does not kill the CLI process. There are two reasons for this:
* we use Node.js's `child_process.spawnSync` method to call `xcrun simctl` commands
* simctl handles the killing signals in its own manner
When the executable passed to spawnSync method has its own logic for handling Signals for termination, Node.js process does not receive the Signals. That's why, the spawned process just exits and CLI's code continues.
However, the returned result has a signal property showing the signal used to kill the process.
In order to send the same signal to CLI, just …

Fix killing simctl process capturing the kill signal without sending to parent

---

lib/declarations.ts
lib/iphone-simulator-common.ts
lib/iphone-simulator-xcode-simctl.ts
lib/simctl.ts
package.json

Part of the fix https://github.com/NativeScript/nativescript-cli/issues/3141#issuecomment-333761544
Fix uses the method described in [this example](https://developer.apple.com/library/content/samplecode/Logging/Listings/Paper_Company_ReadMe_md.html#//apple_ref/doc/uid/TP40017510-Paper_Company_ReadMe_md-DontLinkElementID_11).

Fix log in iOS11 simulators.

---

lib/declarations.ts
lib/iphone-simulator-xcode-simctl.ts
lib/simctl.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/3324

fix(simulator): Boot orphan simulator

---

lib/iphone-simulator-xcode-simctl.ts

Give some time to `simctl launch` command to launch the process and all related processes and services
Trying to fix https://github.com/NativeScript/nativescript-cli/issues/3235

Give some time to `simctl launch` command to launch the process

---

lib/commands/launch.ts
lib/commands/notify-post.ts
lib/declarations.ts
lib/ios-sim.ts
lib/iphone-simulator-name-getter.ts
lib/iphone-simulator-xcode-simctl.ts
lib/iphone-simulator.ts
lib/options.ts
lib/simctl.ts
package.json

The inspector listening socket is being closed 30 sec. after the last activity on it (opening, disconnection, etc). It had to be closed in order to have the hardcoded port number 18181
available for other apps after finishing (or never starting) a
debugging session. Without this timeout the first app that opened
the port would take it as long as it's running and would prevent
any subsequent debugging attempts of another app on the same iOS device;
or even the same app on another iOS Simulator on the same Mac machine.
This leads to unavailability to run fast sync on multiples simulators.
From now on, the port is printed from `ios-runtime` in devices logs. {N} CLI parses the logs and searches for specified string. The string should be in following format:
```
NativeScript debugger has …
```

Get debugger port from device logs

---

lib/iphone-simulator-xcode-simctl.ts
lib/iphone-simulator.ts
package.json

In case `launchApplication` is called with device identifier (instead of name), the validation fails as it expects a name. However, we already support starting and working with Id, so fix the validation.
Also, in the past there was only one instance of a simulator running. When you wanted to start application on another simulator, we were killing the existing one and starting the new one. This is no longer required as multiple iOS Simulators may be running simultaneously. So remove the logic for killing the simulator

fix: launchApplication fails when device identifier is passed

---

lib/ios-sim.ts
package.json

Currently when we want to detect iOS Simulators we have a setInterval that iterrates 30 times for 500ms.
When you do not have any iOS Simulator, this causes 15 seconds of waiting.
Just retry once and continue, if the simulators don't show up, well, they do not want to work with you.

fix: Do not wait 15 seconds to detect simulator

---

lib/commands/device-types.ts
lib/commands/launch.ts
lib/commands/notify-post.ts
lib/commands/sdks.ts
lib/declarations.ts
lib/ios-sim.ts
lib/iphone-simulator-xcode-simctl.ts
lib/iphone-simulator.ts
lib/simctl.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/3545

Make ios-sim API async

---

lib/iphone-simulator-xcode-simctl.ts
package.json

When using Xcode 10, the `xcrun simctl install ...` command fails every other time with error:
```
Error: Command xcrun with arguments simctl install 5516E083-C749-47A7-A6FC-2EE2E414D025 /Users/vladimirov/Work/nativescript-cli/scratch/app1/platforms/ios/build/emulator/app1.app failed with exit code 1. Error output:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/vladimirov/Library/Developer/CoreSimulator/Devices/5516E083-C749-47A7-A6FC-2EE2E414D025/data/Library/Caches/com.apple.mobile.installd.staging/temp.ZdmYQa/extracted/Payload/app1.app
Failed to load Info.plist from bundle at path /Users/vladimirov/Library/Developer/CoreSimulator/Devices/5516 …
```

fix: unable to install application every other time with Xcode 10

---

lib/iphone-simulator-xcode-simctl.ts
package.json

In some cases (especially with Xcode 10), calling getDeviceLogProcess returns a childProcess for the logs, that is not started yet.
This breaks `tns debug ios --start` in CLI as the logs are not sent to the CLI immediately and it fails to find the port for debugging.

fix: log process is not started on getDeviceLogProcess

---

lib/simctl.ts

In case application is not installed on simulator, `xcrun simctl get_app_container ...` command returns some random path that does not exist. In case you install the application after that, the path is not the same as the returned by the command before that.
So check if the path exists and return null in case it does not.

fix: get_app_container returns non-existent path

---

lib/iphone-simulator-xcode-simctl.ts

`childProcess.spawn` is blocking method and waits for close event to resolve the promise. Actually we'll never received `close` event because we want to read log file all the time. So use `child_process.spawn` in order to fix livesync command.

fix: use correct spawn method in order to fix livesync

---

lib/iphone-simulator-xcode-simctl.ts
package.json

In case application name contains `grep`, the `getPid` method will not return any result as we have `grep -v grep` in the executed command.
Also, in case you run `tns run ios --path <path to app> --device <id>`, the `getPid` method will return the pid of CLI's process as well as it maches the criteria.
The fix is to check for `/${deviceId}/` when grep-ing. Also remove the `grep -v grep` and replace it with exclusion of the command we've executed. This is due to the fact that Node.js executes a new shell process and the command executed in `getPid` returns it as well.

fix: getPid returns incorrect result 

---

lib/child-process.ts
lib/declarations.ts
lib/iphone-simulator-xcode-simctl.ts
lib/simctl.ts
package.json

When Xcode Command Line tools are not installed, calling `xcrun` leads to a popup with suggestion to install Xcode Command Line Tools. Prevent this by checking if Xcode is installed and if not - do not spawn `xcrun`.
Fix incorrect interfaces and remove unused method.

fix: popup is shown when searching for iOS Simulators

---

lib/iphone-simulator-common.ts
lib/iphone-simulator-xcode-simctl.ts

this fix let the XCode simulator choose the default simulator to run. 
Which is the last state of the simulator app. (can even be multiple simulators)
Before that it was always choosing the same simulator. 
We now have the same behavior as the simulator app which brings a much better user experience ( imho)

fix: default simulator fix

---

lib/iphone-simulator-xcode-simctl.ts

This fixes a case where `xcrun simctl terminate XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX org.nativescript.app` returns a non-zero exit code peventing the CLI from restarting the app.
Sample log when this occurs:
```
Restarting application on device XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX...
Error while trying to start application org.nativescript.app on device XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX. Error is: Command xcrun with arguments simctl terminate XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX org.nativescript.app failed with exit code 3. Error output:
objc[61078]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x21f3b3678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1059202c8). One of the two will be …
```

fix: ignore non-zero exit code from simctl terminate
